import { test, expect } from '../fixtures/mobileFeedbackTest.js';
import { UtilityAppearanceTab } from '../poms/utilityAppearanceTab.js';
import { MobilePolishPage } from '../poms/mobilePolishPage.js';
import { SettingsModalAppBar } from '../poms/settingsModalAppBar.js';
import { TrackModal } from '../poms/trackModal.js';

// A desktop browser crossing 900px changes profile; a Pixel UA stays mobile.
test.use({ userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/151.0.0.0 Safari/537.36', isMobile: false });

for (const palette of ['black', 'parchment-pine']) {
  test(`appearance drafts and page navigation survive phone/desktop transitions in ${palette}`, async ({ page, app, snapshot }) => {
    const appearance = new UtilityAppearanceTab(page);
    const settings = new SettingsModalAppBar(page);
    const album = new TrackModal(page);
    await new MobilePolishPage(page).usePalette(palette);
    const settingsParentUrl = page.url();
    await app.openSettings();
    const settingsSurface = await settings.modal.elementHandle();
    await appearance.paletteButton('paper').click();
    await app.selectSubsection('album-page');
    await page.setViewportSize({ width: 1280, height: 900 });
    await expect(app.backButton).toBeHidden();
    await expect(app.utilitiesDialogs).toBeVisible();
    await expect(app.utilitiesDialogs).toHaveAttribute('aria-modal', 'true');
    await expect(settings.closeButton).toBeVisible();
    await expect(appearance.sidebar.list).toBeVisible();
    expect(await app.isRetainedSurface(settingsSurface)).toBe(true);
    await expect(appearance.deviceButton('Web / Desktop')).toHaveAttribute('aria-pressed', 'true');
    await expect(app.cancelAppearance).toBeEnabled();
    await snapshot(`80-retained-settings-desktop-${palette}`);
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(app.utilitiesPage).toBeVisible();
    await expect(app.utilitiesDialogs).toHaveCount(0);
    await expect(app.backButton).toBeVisible();
    await expect(app.backGlyph).toHaveCSS('stroke-width', '1.7px');
    await expect(app.backGlyph).toHaveCSS('width', '22px');
    expect(await app.isRetainedSurface(settingsSurface)).toBe(true);
    await expect(app.mobileAppearance).toHaveAttribute('aria-pressed', 'true');
    await expect(appearance.documentRoot).toHaveAttribute('data-appearance-palette', 'paper');
    await app.selectSubsection('backgrounds');
    await expect(appearance.paletteButton('paper')).toHaveAttribute('aria-pressed', 'true');
    await app.cancelAppearance.click();
    await expect(appearance.paletteButton(palette)).toHaveAttribute('aria-pressed', 'true');
    await expect(appearance.documentRoot).toHaveAttribute('data-appearance-palette', palette);
    await app.selectSubsection('seekbar');
    await expect(app.thinOption).toBeVisible();
    await app.expectPlayerPreviewReadable();
    await app.customAppearance.click();
    await app.waveformOption.check();
    await page.setViewportSize({ width: 1280, height: 900 });
    await expect(app.thinOption).toHaveCount(0);
    await expect(app.regularOption).toBeChecked();
    await app.saveAppearanceChanges();
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(app.waveformOption).toBeChecked();
    await page.setViewportSize({ width: 1280, height: 900 });
    await expect(app.utilitiesDialogs).toBeVisible();
    expect(await app.isRetainedSurface(settingsSurface)).toBe(true);
    await settings.closeButton.click();
    await expect(settings.modal).toBeHidden();
    await expect(page).toHaveURL(settingsParentUrl);
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(settings.modal).toBeHidden();
    await expect(app.utilitiesPage).toHaveCount(0);
    await page.setViewportSize({ width: 1280, height: 900 });
    await settingsSurface.dispose();

    // Fresh desktop Settings remains a dialog; shrinking promotes that same surface.
    await app.settingsButton.click();
    await app.utilitiesButton.click();
    await expect(app.utilitiesDialogs).toBeVisible();
    const freshSettingsSurface = await settings.modal.elementHandle();
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(app.utilitiesPage).toBeVisible();
    await expect(app.utilitiesDialogs).toHaveCount(0);
    await expect(app.thinOption).toBeVisible();
    await app.expectPlayerPreviewReadable();
    await expect(app.backButton).toBeVisible();
    await expect(app.backGlyph).toHaveCSS('stroke-width', '1.7px');
    await expect(app.backGlyph).toHaveCSS('width', '22px');
    expect(await app.isRetainedSurface(freshSettingsSurface)).toBe(true);
    await freshSettingsSurface.dispose();
    await snapshot(`81-promoted-settings-phone-${palette}`);
    await app.backButton.click();
    await expect(app.utilitiesPage).not.toBeVisible();
    await expect(app.galleryContextName).toHaveText('Rendref');
    await app.search('After the Rain');
    const albumParentUrl = page.url();
    await app.openAlbumBody('After the Rain');
    const albumSurface = await album.dialog.elementHandle();
    await page.setViewportSize({ width: 1280, height: 900 });
    await expect(app.backButton).toBeHidden();
    await expect(app.albumDialogs).toBeVisible();
    await expect(album.closeButton).toBeVisible();
    expect(await app.isRetainedSurface(albumSurface)).toBe(true);
    await album.closeButton.click();
    await expect(album.dialog).toBeHidden();
    await expect(page).toHaveURL(albumParentUrl);
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(album.dialog).toBeHidden();
    await expect(app.albumPage).toHaveCount(0);
    await page.setViewportSize({ width: 1280, height: 900 });
    await albumSurface.dispose();
    await app.selectView('cards');
    await app.galleryCards.getByRole('button', { name: 'After the Rain', exact: true }).click();
    await expect(app.albumDialogs).toBeVisible();
    const freshAlbumSurface = await album.dialog.elementHandle();
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(app.albumPage).toBeVisible();
    await expect(app.albumDialogs).toHaveCount(0);
    await expect(app.backButton).toBeVisible();
    await expect(app.backGlyph).toHaveCSS('stroke-width', '1.7px');
    await expect(app.backGlyph).toHaveCSS('width', '22px');
    expect(await app.isRetainedSurface(freshAlbumSurface)).toBe(true);
    await freshAlbumSurface.dispose();
    expect(await app.hasNoHorizontalOverflow()).toBe(true);
    await snapshot(`82-promoted-album-phone-${palette}`);
  });
}
