/** Opt-in concepts only. Native renderers, isolated state, no saved preferences. */
import React,{useState} from 'react';
export function ReviewProposals({Action,Choice}){
 const [palette,setPalette]=useState('black'),[period,setPeriod]=useState('week'),[style,setStyle]=useState(''),[love,setLove]=useState('all'),[open,setOpen]=useState(''),[expanded,setExpanded]=useState(false);
 const periods=[{value:'week',label:'Last week'},{value:'month',label:'Last month'},{value:'all',label:'All time'}],styles=[{value:'',label:'Any style'},{value:'ambient',label:'Ambient'},{value:'rock',label:'Rock'}],loves=[{value:'all',label:'Loved + obsessed'},{value:'loved',label:'Loved'},{value:'obsessed',label:'Obsessed'}];
 const filters=<><Choice label="Love" density="slim" value={love} options={loves} onChange={setLove}/><Choice label="Style" density="slim" value={style} options={styles} onChange={setStyle}/><Choice label="Period" density="slim" value={period} options={periods} onChange={setPeriod}/></>;
 return <section className="mock-proposals" aria-labelledby="mock-proposals-title"><header className="mock-proposals-heading"><a href="/?mock=home">Return to normal mock</a><h1 id="mock-proposals-title">Design proposals</h1><p>Interactive concepts using the app's real components. These choices are not applied to the normal mock. Rendered screenshots are still pending.</p></header>
 <section className="mock-module"><header className="mock-module-header"><h2>Icon preview</h2></header><img src="/icon-source-preview.svg" alt="Source-rendered Album statistics clasped-hands and Obsessed flaming-heart icons at18,24and48pixels on dark and light backgrounds"/><p className="mock-proposal-copy">SVG source preview. This is not an application screenshot.</p></section>
 <section className="mock-module"><header className="mock-module-header"><h2>Panel surfaces</h2><Choice label="Palette proposal" density="slim" value={palette} options={[{value:'black',label:'Black'},{value:'navy',label:'Blue'},{value:'parchment-pine',label:'Parchment'}]} onChange={setPalette}/></header><p className="mock-proposal-copy">Modules use the same native palette surface as the outer app bar and sidebar. Change the palette to compare the actual Home composition.</p><iframe key={palette} title={`${palette} native panel-color concept`} src={`/?mock=home&mock_proposal=panel-color&proposal_palette=${palette}`} className="mock-proposal-frame"/><a href={`/?mock=home&mock_proposal=panel-color&proposal_palette=${palette}`}>Open this native preview at full size</a></section>
 <section className="mock-module"><header className="mock-module-header"><h2>Back and expand placement</h2></header><div className="mock-proposal-options"><div><h3>A · Back left, Collapse right</h3><header className="mock-proposal-native-header"><Action label="Back in concept A" icon="back" bare onClick={()=>setExpanded(false)}/><strong>Recent albums</strong><div className="mock-header-actions"><Action label="Collapse in concept A" icon="collapse" onClick={()=>setExpanded(false)}/></div></header><p>Separate return and layout actions, with the expanded view's origin preserved.</p></div><div><h3>B · One layout action left</h3><header className="mock-proposal-native-header"><Action label={expanded?'Collapse in concept B':'Expand in concept B'} icon={expanded?'collapse':'expand'} bare onClick={()=>setExpanded(!expanded)}/><strong>Recent albums</strong></header><p>The left action changes between Expand and Collapse. Browser Back remains available.</p></div></div></section>
 <section className="mock-module"><header className="mock-module-header"><h2>Playlist filter options</h2></header><div className="mock-proposal-options"><div><h3>A · Compact grouped toolbar</h3><div className="mock-proposal-filter-group">{filters}</div><p>All three common choices remain visible in a right-aligned group.</p></div><div><h3>B · Filters and active summary</h3><div className="mock-proposal-filter-group"><span>{love==='all'?'Loved + obsessed':love} · {style||'Any style'}</span><Action label="Show filter popover concept" icon="filter" onClick={()=>setOpen(open==='popover'?'':'popover')}/></div>{open==='popover'&&<div className="mock-proposal-filter-popover" role="region" aria-label="Filter popover concept">{filters}</div>}<p>One control and a readable summary; the choices appear together when opened.</p></div><div><h3>C · Collapsible filter row</h3><div className="mock-proposal-filter-group"><Action label={open==='drawer'?'Hide filter row concept':'Show filter row concept'} icon="filter" active={open==='drawer'} onClick={()=>setOpen(open==='drawer'?'':'drawer')}/><span>Filters</span></div>{open==='drawer'&&<div className="mock-proposal-filter-drawer">{filters}</div>}<p>The optional row expands above the table and closes when more space is useful.</p></div></div></section>
 </section>;
}
